# Generated by Django 5.2.5 on 2025-08-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('READING', 'Reading'), ('QUIZ', 'Quiz')], max_length=10)),
                ('order_index', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('course', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='QuizLecture',
            fields=[
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quiz_lecture', serialize=False, to='lectures.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLecture',
            fields=[
                ('lecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reading_lecture', serialize=False, to='lectures.lecture')),
                ('content_text', models.TextField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lecture_files/')),
            ],
        ),
    ]
