# Generated by Django 5.2.5 on 2025-08-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglecture',
            name='content_text',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('VIDEO', 'Video'), ('PDF', 'PDF')], max_length=10),
        ),
    ]
