# Generated by Django 5.2.5 on 2025-08-22 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_remove_readinglecture_content_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlecture',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='quizlecture',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the quiz closes'),
        ),
        migrations.AddField(
            model_name='quizlecture',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the quiz becomes available'),
        ),
    ]
