# Generated by Django 5.2.5 on 2025-08-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lecture_ids', models.JSONField(default=list)),
                ('scores', models.JSONField(default=dict)),
                ('last_seen_lecture_id', models.IntegerField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='enrollments.enrollment')),
            ],
        ),
    ]
